name: NuGet Generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Update NuGet package
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build solution and generate NuGet package
        run: |  
          cd <project>
          dotnet pack -c Release -o out  
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Changes in this Release
          draft: false
          prerelease: false